django_orm_mastery/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('inventory/', include('inventory.urls', namespace='inventory'))
]

inventory/urls.py
from django.urls import path

from . import views

app_name = "inventory"

urlpatterns = [
    path("", views.get_categories, name="get_categories"),
    path("create_product", views.create_product, name="create_product"),
    path("create_stock", views.create_stock, name="create_stock"),
    path("reverse_query", views.reverse_query, name="reverse_query"),
]

inventory/models.py
from django.db import models
from .fields import ProductDescriptionField

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=50)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    date_updated = models.DateTimeField(auto_now=True)
    url = models.SlugField(null=True, blank=True)
    is_active = models.BooleanField(default=True)
    quantity = models.IntegerField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, blank=True)
    description = ProductDescriptionField()
    # To set a verbose name for a field you can do this
    # name = models.CharField("brand_name", max_length=100)

    # To create a many to many field you can do this, creating a many to many field will create a link table
    # category = models.ManyToManyField(Category)

    def __str__(self):
        return f"{self.name} - {self.category.name}"

class Brand(models.Model):
    # You can explicitly define your primary key like this. See example below.
    # brand_id = models.BigAutoField(primary_key=True)
    name = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.id} - {self.name}"

class Stock(models.Model):
    units = models.BigIntegerField()
    product = models.OneToOneField(Product, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.product} - {self.units}"

user/models.py
from django.db import models

# Create your models here.
class Person(models.Model):

    # RED = 'RD'
    # BLUE = 'BL'

    # FAV_COLOR = [
    #     (RED, 'red'),
    #     (BLUE, 'blue')
    # ]

    # to create a Person object via shell, you can access the constants inside this class.
    # Example: Person.objects.create(name='test', color=Person.BLUE)

    # -------------------------------------------------------------------------
    # Alternative approach
    class Colours(models.TextChoices):
        RED = 'RD', 'Red'
        BLUE = 'BL', 'Blue'

    name = models.CharField(max_length=50)
    color = models.CharField(max_length=50, choices=Colours.choices)

    def __str__(self):
        return f"{self.name} - {self.color}"

    # to create a Person object via shell, you can access the constants inside the Colours class.
    # Example: Person.objects.create(name='test', color=Person.Colours.BLUE)

inventory/forms.py
from django import forms

class CreateProductForm(forms.Form):
    name = forms.CharField(label="name", max_length=100)
    price = forms.DecimalField(label="price", max_digits=10, decimal_places=2)
    url = forms.SlugField(label="url")
    quantity = forms.IntegerField(label="quantity", max_value=50)
    categories = forms.CharField(label="categories", max_length=255)

class CreateStockForm(forms.Form):
    units = forms.IntegerField(label="units")
    product = forms.CharField(label="product", max_length=100)

inventory/views.py
from django.http import HttpResponse
from django.shortcuts import render
from pygments import highlight
from pygments.formatters import TerminalFormatter
from pygments.lexers import MySqlLexer
from sqlparse import format

from .forms import CreateProductForm, CreateStockForm
from .models import Category, Product, Stock


# Create your views here.
def get_categories(request):

    all_category = Category.objects.all()
    sql_formatted = format(str(all_category.query), reindent=True)
    print(highlight(sql_formatted, MySqlLexer(), TerminalFormatter()))

    return HttpResponse(all_category.query)

def create_product(request):
    # create() is often use together with a form

    all_category = Category.objects.all()
    message = ""

    if request.method == "POST":
        form = CreateProductForm(request.POST)

        if form.is_valid() == True:
            form_data = form.cleaned_data
            try:
                category = Category.objects.get(name=form_data["categories"])

                Product.objects.create(
                    name = form_data["name"],
                    price = form_data["price"],
                    url = form_data["url"],
                    quantity = form_data["quantity"],
                    category = category
                )
                message = "Product successfully created!"
                # Alternative approach using save()
                # product = Product(
                #     name = form_data["name"],
                #     price = form_data["price"],
                #     url = form_data["url"],
                #     quantity = form_data["quantity"],
                #     category = category
                # )
                # product.save()
                # note: save() method can also be used when updating a record
            except Category.DoesNotExist:
                message = "Category does not exist"
            except Exception as e:
                message = f"An error occurred: {str(e)}"
        else:
            message = "Form is invalid. Please correct the errors."
    else:
        form = CreateProductForm()

    context = {
        "form": form,
        "all_category": all_category,
        "message": message
    }

    return render(request, "create_product.html", context)

def create_stock(request):

    all_product = Product.objects.all()
    all_stock = Stock.objects.all()
    message = ""

    if request.method == "POST":
        form = CreateStockForm(request.POST)

        if form.is_valid() == True:
            try:
                product = Product.objects.get(name=form.cleaned_data["product"])

                Stock.objects.create(
                    units = form.cleaned_data["units"],
                    product = product
                )
                message = "Stock created successfully!"
            except Product.DoesNotExist:
                message = "Product does not exist"
            except Exception as e:
                message = f"An error occurred {str(e)}"
        else:
            message = "Form is invalid. Please correct the errors."
    else:
        form = CreateStockForm()

    context = {
        "form": form,
        "all_product": all_product,
        "all_stock": all_stock,
        "message": message
    }

    return render(request, "create_stock.html", context)

def reverse_query(request):
    # Using "_set" to get related products to cat1 if the related name is not set on the field.

    cat1 = Category.objects.get(pk=1)
    related_products = cat1.product_set.all()
    print(related_products)

    return HttpResponse(related_products)

user/views.py
from django.shortcuts import render

# Create your views here.

inventory/templates/create_product.html
{% extends 'main.html' %}
{% block content %}
    <form action="{% url 'inventory:create_product' %}" method="post">
        {% csrf_token %}
        <div>
            <label for="name">Name:</label>
            <input type="text" id="name" name="name" value="{{ form.name.value }}">
            {{ form.name.errors }}
        </div>
        <div>
            <label for="price">Price:</label>
            <input type="number" id="price" name="price" value="{{ form.price.value }}">
            {{ form.price.errors }}
        </div>
        <div>
            <label for="url">URL:</label>
            <input type="text" id="url" name="url" value="{{ form.url.value }}">
            {{ form.url.errors }}
        </div>
        <div>
            <label for="quantity">Quantity:</label>
            <input type="number" id="quantity" name="quantity" value="{{ form.quantity.value }}">
            {{ form.quantity.errors }}
        </div>
        <div>
            <label for="categories">Categories: </label>
            <select name="categories" id="categories">
                {% for cat in all_category %}
                    <option value="{{ cat.name }}" {% if form.categories.value == cat.name %}selected{% endif %}>{{ cat.name }}</option>
                {% endfor %}
            </select>
            {{ form.categories.errors }}
        </div>
        <div>
            <input type="submit" value="Save">
        </div>
    </form>
    {% if message %}
        <p>{{ message }}</p>
    {% endif %}
{% endblock %}

inventory/templates/create_stock.html
{% extends 'main.html' %}
{% block content %}
    <form action="{% url 'inventory:create_stock' %}" method="post">
        {% csrf_token %}
        <div>
            <label for="units">Units:</label>
            <input type="number" id="units" name="units" value="{{ form.units.value }}">
            {{ form.units.errors }}
        </div>
        <div>
            <label for="product">Product: </label>
            <select name="product" id="product">
                {% for prod in all_product %}
                    <option value="{{ prod.name }}" {% if form.product.value == prod.name %}selected{% endif %}>{{ prod.name }}</option>
                {% endfor %}
            </select>
            {{ form.product.errors }}
        </div>
        <div>
            <input type="submit" value="Save">
        </div>
    </form>
    {% if message %}
        <p>{{ message }}</p>
    {% endif %}
    {% if all_stock %}
        <h4>All Stocks</h4>
        <ul>
            {% for stock in all_stock %}
                <li>{{ stock.product.name }} - {{ stock.units }}</li>
            {% endfor %}
        </ul>
    {% endif %}
{% endblock %}

inventory/templates/main.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
    </head>
    <body>
        {% block content %}
        {% endblock %}
    </body>
</html>